apiVersion: apps/v1
kind: Deployment
metadata: 
    name: Kube1_deploy
spec:
    replicas: 3
    selector:
      matchLabels:
        app: Kube1_deploy
    template:
      metadata:
        labels:
          app: devops1
        spec:
          containers:
          - name: devops1
            image: sujetha/pineline_demo1
            imagePullPolicy: Always
            ports:
            - containerPort: 80


          