kind: Service                             
apiVersion: v1
metadata:
  name: Kube1_deploy
  labels:
    app: Kube1_deploy
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: Kube1_deploy                    
  type: LoadBalancer                   
