kind: Service                             
apiVersion: v1
metadata:
  name: devops1
  labels:
    app: devops1
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: devops1                    
  type: LoadBalancer                   
